### ISSUE TITLE
pi1 not compatible with armhf 

### ISSUE THREAD

**Issue by kmlucy** [linuxserver/docker-unifi-armhf#4] opened 2016-12-13 17:02 UTC
OS: Raspbian Jessie

Run command:
```
docker run --name=unifi -v /opt/unifi:/config -e PGID=1000 -e PUID=1000 -p 8080:8080 -p 8081:8081 -p 8443:8443 -p 8843:8843 -p 8880:8880 lsioarmhf/unifi
```

Logs: 
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
[cont-init.d] 10-adduser: exited 260.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 260.
[cont-init.d] 30-keygen: executing...
[cont-init.d] 30-keygen: exited 260.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

This is on a fresh install of Raspbian Jessie. I am unable to access the controller at https://ip:8443, and the ```/opt/unifi``` folder is empty

Thanks,
Kyle

**Comment by sparklyballs** [comment] 2016-12-13 17:06
wait....

it can take quite a long time to generate keys etc

**Comment by kmlucy** [comment] 2016-12-13 17:07
I left it for about an hour at one point. Does it typically take longer than that?

Thanks,
Kyle

**Comment by sparklyballs** [comment] 2016-12-13 17:07
either that or ensure that the user with the 1000 id (pi i assume) has permissions on /opt

**Comment by sparklyballs** [comment] 2016-12-13 17:08
i'm not sure how it works if you stop it and retry again without pulling a new copy of the docker.

**Comment by sparklyballs** [comment] 2016-12-13 17:09
the time varies, the longest i can remember when testing was ~ 20 minutes on a RPi3

**Comment by sparklyballs** [comment] 2016-12-13 17:11
also, your run command doesn't have -d in it.

i'd recommend that and using `docker logs -f unifi`

**Comment by sparklyballs** [comment] 2016-12-13 17:12
`exited 260`

i'm not sure what code is, but i suspect perms

**Comment by kmlucy** [comment] 2016-12-13 17:18
Yes, pi has uid 1000 and gid 1000 and is the owner and group of ```/opt/unifi```. 
```
$ ls -l /opt
drwxr-xr-x 2 pi   pi   4.0K Dec 13 15:41 unifi
$ id pi
uid=1000(pi) gid=1000(pi) groups=1000(pi), ... ,996(docker)
```

When I retried, it was by stopping and removing the container, and then recreating the container from scratch, not just stopping and starting it.

The run command doesn't have the -d in it because it is through a systemd unit file. I use that to start and stop the container, then use -f on the logs.

**Comment by sparklyballs** [comment] 2016-12-13 17:18
can you give me the output of `id pi`

**Comment by sparklyballs** [comment] 2016-12-13 17:19
no worries, you have.

need to put my glasses on...

**Comment by kmlucy** [comment] 2016-12-13 17:19
No problem

**Comment by sparklyballs** [comment] 2016-12-13 17:21
have you tried it direct on the command line and not using systemd ?

i don't know what exited 260 means and google isn't helping so far.

**Comment by sparklyballs** [comment] 2016-12-13 17:23
`pi@raspberrypi3:~ $ docker run --name=unifi -v /opt/unifi:/config -e PGID=1000 -e PUID=1000 -p 8080:8080 -p 8081:8081 -p 8443:8443 -p 8843:8843 -p 8880:8880 lsioarmhf/unifi
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/index.php/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
^C[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.`

i crtl-c'd when it got to line 30

that is your run command verbatim on the command line with no prior folder of /opt/unifi

**Comment by kmlucy** [comment] 2016-12-13 17:28
I tried it both straight through the command line:
```
docker run -d --name=unifi -v /opt/unifi:/config -e PGID=1000 -e PUID=1000 -p 8080:8080 -p 8081:8081 -p 8443:8443 -p 8843:8843 -p 8880:8880 lsioarmhf/unifi
```

And then again without the volume mount:
```
docker run -d --name=unifi -e PGID=1000 -e PUID=1000 -p 8080:8080 -p 8081:8081 -p 8443:8443 -p 8843:8843 -p 8880:8880 lsioarmhf/unifi
```

And both times I got the same output with the 260 exit codes. I had tried to look that code up earlier and didn't have any luck either.

**Comment by kmlucy** [comment] 2016-12-13 17:30
And the same result with the most basic command I could use:
```
docker run -d --name=unifi lsioarmhf/unifi
```

**Comment by sparklyballs** [comment] 2016-12-13 17:31
can you try it after su to root ?

**Comment by sparklyballs** [comment] 2016-12-13 17:35
the only other thing i can think of is the install method for docker.

https://www.raspberrypi.org/blog/docker-comes-to-raspberry-pi/

has the preferred method

**Comment by kmlucy** [comment] 2016-12-13 17:37
```
$ sudo su
# docker run -d --name=unifi lsioarmhf/unifi
``` 
had the same result.

That article is how I installed docker.

**Comment by kmlucy** [comment] 2016-12-13 17:38
```
$ docker version
Client:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Tue Dec 13 00:31:14 2016
 OS/Arch:      linux/arm

Server:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Tue Dec 13 00:31:14 2016
 OS/Arch:      linux/arm
```

**Comment by sparklyballs** [comment] 2016-12-13 17:39
i'm frankly at a loss, i can't find any exit codes beyond 256 anywhere and i can't reproduce on either of my two pi3's

**Comment by kmlucy** [comment] 2016-12-13 17:43
This is a B+. I believe the architecture is the same, and I was able to run the controller bare metal before. Could that be the issue?

**Comment by kmlucy** [comment] 2016-12-13 17:55
I was able to run hypriot/rpi-busybox-httpd correctly, just as a test that it wasn't all images failing.

**Comment by kmlucy** [comment] 2016-12-13 22:42
So it appears than no command is working:
```
$ docker run lsioarmhf/unifi echo test
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
[cont-init.d] 10-adduser: exited 260.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 260.
[cont-init.d] 30-keygen: executing...
[cont-init.d] 30-keygen: exited 260.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
echo exited 260
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

I've tried several basic commands that should work, including ```/bin/bash```, and they all exit 260. I tried removing the image and pulling it again in case it was corrupt, but got the same result. I even tried pulling the image on another server, saving, copying, then loading it on the pi, with the same result.

**Comment by sparklyballs** [comment] 2016-12-13 22:45
yeah, i'm stumped as to what exited 260 is.

can you try another of our containers ?

https://hub.docker.com/r/lsioarmhf/sonarr/

for instance

**Comment by kmlucy** [comment] 2016-12-13 23:07
I think I found the problem. The base image is based on armv7/armhf-ubuntu, which appears to only be compatible with armv7, and not armv6, which the original pi's were based on. It looks like the images are just not compatible with the 1st generation pi's.

**Comment by sparklyballs** [comment] 2016-12-13 23:11
in that case, there's not a great deal we can do about it.

to be fair though, they are marked as armhf. 

i'm not that familiar with the pi1 , i came to pi on pi2.

**Closed** 2016-12-13 23:11 UTC

**Comment by kmlucy** [comment] 2016-12-13 23:13
The pi1 is still armhf, just a previous version apparently. I wasn't aware there were differences prior to now.
